<?php //die('das'); ?>
<style type="text/css">
	
	.owl-carousel .item img
	{
		border-radius: 5px;
		 width: 100%;
	  height: 400px;
	}

</style>
 <link  rel="stylesheet" type="text/css"  media="all" href="https://www.scanpan.co.za/static/frontend/ScanpanTheme/Scanpan/en_GB/V4U_OwlCarousel/css/owl.carousel.css" />
 <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.js" integrity="sha256-kiFgik3ybDpn1VOoXqQiaSNcpp0v9HQZFIhTgw1c6i0=" crossorigin="anonymous"></script> 


<div class="owl-carousel owl-theme test">
    <div class="item"><img src="https://cdn.pixabay.com/photo/2017/11/23/07/46/babe-2972219_960_720.jpg" alt="first" /></div>
    <div class="item"><img src="https://cdn.pixabay.com/photo/2018/08/18/08/05/boy-3614307_960_720.jpg" alt="second"/></div>
    <div class="item"><img src="https://cdn.pixabay.com/photo/2017/08/12/18/53/turtle-2635026_960_720.jpg" alt="third"/></div>
    <div class="item"><img src="https://images.unsplash.com/photo-1554941426-e9604e34bc94?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80" alt="fourth"/></div>
    <div class="item"><img src="https://images.unsplash.com/photo-1444465693019-aa0b6392460d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80" alt="Fifth"/></div>
    <div class="item"><img src="https://images.unsplash.com/photo-1558981403-c5f9899a28bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80" alt="Sixth"/></div>
    <div class="item"><img src="https://images.unsplash.com/photo-1575301926333-df57978bafb7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80" alt="Seventh"/></div>
</div>
<script type="text/javascript">
//	require(['jquery', 'cpowlcarousel'], function ($) {
                jQuery(document).ready(function () {
                   jQuery('.test').owlCarousel({
                   	 autoPlay: 3000, //Set AutoPlay to 3 seconds
 
				      items : 1,
				      itemsDesktop : [1199,3],
				      itemsDesktopSmall : [979,3]
					});
                });
  //          });
</script>
